-- Run this script in the Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    company_slug TEXT NOT NULL UNIQUE,
    logo TEXT,
    created_by TEXT,
    email TEXT,
    password TEXT NOT NULL,
    theme_color1 TEXT,
    theme_color2 TEXT,
    social_links JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    emp_name TEXT NOT NULL,
    emp_slug TEXT NOT NULL,
    designation TEXT,
    phone TEXT,
    email TEXT,
    photo TEXT,
    card_data JSONB,
    emp_code TEXT,
    otp_code TEXT,
    otp_expiry TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: Ensure Row Level Security (RLS) is configured as per your requirements,
-- or disable it (NOT RECOMMENDED for production if using public anon key).
-- Since the backend uses the service key or runs server-side, it will bypass RLS.
